---
title: "STATS402 Project1 Attempt:Google Analytics"
author: "Naiyu Niu, Kaustubh Deshpande, Jonathan Shan, Stephanie Lao"
date: "10/19/2021"
output:
  html_document:
    df_print: paged
---

# Modeling
```{r}
library(car)


# omit_list = c(sofifa_id, gk_diving, gk_handling,gk_kicking,gk_reflexes,gk_speed,gk_positioning)
data <- read.csv("players_21.csv")
temp <- Filter(is.numeric, data)
num_data <- subset(temp, select = -c(sofifa_id, gk_diving, gk_handling,gk_kicking,gk_reflexes,gk_speed,gk_positioning))
```


```{r}
train <- na.omit(num_data)
pr_train_data <- subset(train, select = -c(wage_eur))
pca_train <- prcomp(pr_train_data)
summary(pca_train)
```

```{r}
round(pca_train$sdev,3)

plot(100*(pca_train$sdev^2/sum(pca_train$sdev^2)), type="l",ylab="Percentage of Variation explained", xlab="PC number")
```


```{r}
rmse <- function(x,y) sqrt(mean((x-y)^2))
set.seed(2021)
options(warn=-1)
cv3_data  = data.frame(pca_train$x)
cv3_data$wage_eur <- train$wage_eur

a <- numeric(3)
b <- numeric(3)
c <- numeric(3)
d <- numeric(3)
for (i in 1:3) {
  newdata <- cv3_data[, -c((i+1):53)]
  model <- glm(wage_eur ~ ., data = newdata)
  a[i] <- cv.glm(newdata, model, K = 6)$delta
  b[i] <- cv.glm(newdata, model)$delta
  c[i] <- rmse(model$fit, newdata$wage_eur)
  d[i] <- AIC(model)
}

# a_min <- min(a)
# b_min <- which.min(b)

par(mfrow=c(2,2))
plot(a, ylab="6-fold CV",xlab="PC number", col=ifelse(a==min(a), "red", "black"))
plot(b, ylab="PRESS statistic or LOOCV",xlab="PC number", col=ifelse(b==min(b), "red", "black"))
plot(c, ylab="RMSE",xlab="PC number", col=ifelse(c==min(c), "red", "black"))
plot(d, ylab="AIC",xlab="PC number", col=ifelse(d==min(d), "red", "black"))
```



```{r}
final_pcr <- glm(wage_eur ~ ., data = cv3_data[, -c((3):53)])
summary(final_pcr)

rmse(final_pcr$fit, train$wage_eur)

linear_mod  <- lm(wage_eur ~ ., train)
summary(linear_mod)
step_mod <- step(linear_mod)

summary(step_mod)
rmse(step_mod$fit, train$wage_eur)
a <- c(step_mod$fitted.values)
b <- train$wage_eur

ab <- data.frame(a = a , b = b)
```

